services:
  api:
    container_name: api
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/app
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - postgres
      - redis
      - mailpit
    restart: unless-stopped

  postgres:
    container_name: postgres
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=fastapi_db
      - POSTGRES_USER=fastapi_user
      - POSTGRES_PASSWORD=fastapi_password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fastapi_user -d fastapi_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailpit:
    container_name: mailpit
    image: axllent/mailpit:latest
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Interface Web
    volumes:
      - mailpit_data:/data

volumes:
  postgres_data:
  redis_data:
  mailpit_data:
